export const orderMock = {
  id: 1,
  phone: "+123456789",
  userId: "5a79aeea-d23b-4490-a318-b6da202c4d24",
  addressId: 1,
  orderPizzas: [
    {
      id: 1,
      name: "Салями-Ветчина",
      quantity: 1,
      sauce: {
        id: 2,
        name: "Сливочный",
        price: 50,
        value: "creamy",
      },
      dough: {
        id: 2,
        name: "Толстое",
        image: "/public/img/dough-large.svg",
        description: "Из твердых сортов пшеницы",
        price: 300,
        type: "large",
        prepositional: "толстом",
      },
      size: {
        id: 2,
        name: "32 см",
        image: "/public/img/diameter.svg",
        multiplier: 2,
        type: "normal",
      },
      ingredients: [
        {
          id: 2,
          name: "Чеддер",
          image: "/public/img/filling/cheddar.svg",
          price: 42,
          nameLat: "cheddar",
          quantity: 3,
        },
        {
          id: 3,
          name: "Томаты",
          image: "/public/img/filling/tomatoes.svg",
          price: 35,
          nameLat: "tomatoes",
          quantity: 3,
        },
        {
          id: 9,
          name: "Салями",
          image: "/public/img/filling/salami.svg",
          price: 42,
          nameLat: "salami",
          quantity: 1,
        },
        {
          id: 8,
          name: "Ветчина",
          image: "/public/img/filling/ham.svg",
          price: 42,
          nameLat: "ham",
          quantity: 1,
        },
      ],
      price: 1330,
    },
  ],
  orderMisc: [
    {
      miscId: 1,
      name: "Cola-Cola 0,5 литра",
      quantity: 1,
      price: 56,
      image: "/public/img/cola.svg",
    },
    {
      miscId: 2,
      name: "Острый соус",
      quantity: 2,
      price: 10,
      image: "/public/img/sauce.svg",
    },
    {
      miscId: 3,
      name: "Картошка из печи",
      quantity: 3,
      price: 170,
      image: "/public/img/potato.svg",
    },
  ],
  orderAddress: {
    id: 1,
    name: "Дом",
    street: "Уральских Рабочих11",
    building: "3311",
    flat: "1",
    comment: null,
    userId: "5a79aeea-d23b-4490-a318-b6da202c4d24",
  },
};
