export const SET_ENTITY = "SET_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const SET_DND_TRANSFER_DATA = "SET_DND_TRANSFER_DATA";
export const SET_PIZZA = "SET_PIZZA";
export const EDIT_PIZZA = "EDIT_PIZZA";
export const RESET_ACTIVE = "RESET_ACTIVE";
export const RESET_CART = "RESET_CART";
